display:
  wallpapers_dir: .config/dude/wallpapers/
  screensaver_timeout_secs: 300
  brightness:
    ac: 100
    battery: 20
  profiles:
    home-office:
      eDP1:
        resolution: auto
      HDMI1:
        resolution: auto
        extra_args: --right-of eDP1
    single:
      eDP1:
        resolution: auto
input:
  keyboards:
    mechanical:
      default: true
      model: pc105
      layout: us
    builtin:
      model: thinkpad60
      layout: br
  mouse:
    natural_scrolling: true
terminal:
  font: Source Code Pro
  font_size: 12

